# Generated by Django 6.0.2 on 2026-03-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male (assigned at birth)'), ('female', 'FEMALE (assigned at birth)')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (1-3 days/week)'), ('moderate', 'Moderately active (3-5 days/week)'), ('very', 'Very active (6-7 days/week)'), ('extra', 'Extra active (very intense exercise daily)')], max_length=10)),
                ('bmr', models.FloatField()),
                ('goal', models.CharField(choices=[('lose', 'Weight Loss'), ('gain', 'Weight Gain'), ('maintain', 'Maintain Weight')], max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('target_calories', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
