# Generated by Django 6.0.2 on 2026-03-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('anxiety_level', models.IntegerField(choices=[(1, 'Not Anxious At All'), (2, 'Not Anxious'), (3, 'Slightly Anxious'), (4, 'Somewhat Anxious'), (5, 'Anxious'), (6, 'Moderately Anxious'), (7, 'Quite Anxious'), (8, 'Very Anxious'), (9, 'Super Anxious'), (10, 'Extremely Anxious')])),
                ('stress_level', models.IntegerField(choices=[(1, 'Not Stressed At All'), (2, 'Not Stressed'), (3, 'Slightly Stressed'), (4, 'Somewhat Stressed'), (5, 'Stressed'), (6, 'Moderately Stressed'), (7, 'Quite Stressed'), (8, 'Very Stressed'), (9, 'Super Stressed'), (10, 'Extremely Stressed')])),
                ('overall_mood', models.IntegerField(choices=[(1, 'Poor'), (2, 'Somewhat Poor'), (3, 'Okay'), (4, 'Somewhat Happy'), (5, 'Happy')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
