# Generated by Django 6.0.2 on 2026-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety Management'), ('stress', 'Stress Relief'), ('mood', 'Mood Improvement'), ('exercise', 'Physical Activity'), ('nutrition', 'Healthy Eating'), ('sleep', 'Sleep Quality'), ('mindfulness', 'Mindfulness & Meditation')], max_length=20)),
                ('min_anxiety_trigger', models.IntegerField(blank=True, null=True)),
                ('min_stress_trigger', models.IntegerField(blank=True, null=True)),
                ('max_mood_trigger', models.IntegerField(blank=True, null=True)),
                ('trigger_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
